### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by butonic**
The make generate works locally, but it failed when adding the new doc index ... trying in this pr

### CODE REVIEW

**Comment by butonic** [comment]
not the cause of make generate errors

**Comment by butonic** [comment]
But we might be able to fix the static check

**Comment by butonic** [comment]
now protobuf api coming in ... https://blog.golang.org/protobuf-apiv2

and tools have not yet catched up.

**Comment by butonic** [comment]
Also reported in https://github.com/protocolbuffers/protobuf/issues/7383

**Comment by refs** [comment]
@butonic see https://github.com/dominikh/go-tools/commit/7e758a3887f90d0ded5f0446112616758183866b

**Comment by butonic** [comment]
superseded by https://github.com/owncloud/ocis-hello/pull/68

**Pull request closed without merging**
