### PR TITLE
Bump JS dependencies, update UI, fix web-config docs

### PR DESCRIPTION
**Pull request by pascalwengerter**
- Bumped ODS to `v12.x.x` and updated UI to reflect changes (icon update & UiKit removal)
- Updated UI extension config to reflect new `web` extension logic
- Updated "Running" docs to reflect current `web` config
- Updated minor JS dependencies

### CODE REVIEW

**Review by wkloucek — APPROVED** [review]
:muscle:

**Comment by wkloucek** [comment]
@pascalwengerter is there any chance that you give this another try? :hugs:

**Comment by pascalwengerter** [comment]
> @pascalwengerter is there any chance that you give this another try? 🤗

Yes please. Can't promise I get anywhere before the `v1.18` release in oCIS though..

**Comment by pascalwengerter** [comment]
@wkloucek @kulmann how relevant is the `ocis-hello` project/repo? It hasn't seen work in almost a year, meanwhile oCIS has reached GA. If you're planning on archiving it feel free to close this PR

**Comment by kulmann** [comment]
> @wkloucek @kulmann how relevant is the `ocis-hello` project/repo? It hasn't seen work in almost a year, meanwhile oCIS has reached GA. If you're planning on archiving it feel free to close this PR

I'd vote for archiving the extension. Can be reworked when we'll have the time to work on the ocis extension system. That's unlikely in the next 6 months.

@micbar what do you think? Can/should we archive the ocis-hello repo and remove it from the dev docs?

**Pull request closed without merging**
